import type { Facility } from "@/types";

export const facilities: Facility[] = [
  {
    slug: "elevator",
    name: "电梯",
    icon: "梯",
    summary: "每天高频运转，也是居民最容易感知的服务。",
    description: "关注运行健康、维护周期和高峰压力，在预防保养与故障抢修之间安排预算。",
    focus: ["设备健康", "维保计划", "高峰效率"],
    event: "早高峰时，一部电梯突然停运。是立即高价抢修，还是先引导居民分流？",
    tone: "green",
  },
  {
    slug: "parking",
    name: "停车场",
    icon: "车",
    summary: "一块有限空间，连接秩序、收益与邻里情绪。",
    description: "调整车位分配、访客规则和出入口效率，处理长期占位与临时停车矛盾。",
    focus: ["车位周转", "通行效率", "居民公平"],
    event: "周末访客车辆排起长队，固定车位业主也被堵在入口。规则要临时调整吗？",
    tone: "blue",
  },
  {
    slug: "locker",
    name: "快递柜",
    icon: "件",
    summary: "方便了收件，也带来了满柜、滞留和空间问题。",
    description: "观察柜体容量与包裹周转，协调快递员、居民和公共空间的不同需求。",
    focus: ["柜体容量", "包裹滞留", "服务体验"],
    event: "促销季快递柜持续爆满，大堂开始堆件。要扩容，还是先优化滞留规则？",
    tone: "orange",
  },
  {
    slug: "camera",
    name: "摄像头",
    icon: "巡",
    summary: "守护公共区域，也需要平衡覆盖、维护与边界。",
    description: "管理关键点位覆盖和设备在线率，用有限资金保障真正重要的公共区域。",
    focus: ["点位覆盖", "设备在线", "公共安全"],
    event: "儿童区附近的摄像头频繁离线，而本月维护预算已经见底。先修哪一处？",
    tone: "blue",
  },
  {
    slug: "playground",
    name: "儿童活动区",
    icon: "乐",
    summary: "承载社区活力，也考验安全、噪声和开放时间。",
    description: "维护游乐设施与场地卫生，在儿童需求和周边住户的安静诉求间找到平衡。",
    focus: ["设施安全", "场地活力", "噪声平衡"],
    event: "新的活动设施很受欢迎，但临近楼栋开始投诉傍晚噪声。是否缩短开放时间？",
    tone: "orange",
  },
  {
    slug: "charging",
    name: "充电桩",
    icon: "电",
    summary: "面向未来的便利设施，背后是容量与安全压力。",
    description: "安排建设批次、巡检频率和使用规则，回应不断增长的充电需求。",
    focus: ["供需容量", "用电安全", "建设成本"],
    event: "新能源车增加得比预期更快。预算只够扩建或加强巡检，应该先做哪一项？",
    tone: "green",
  },
];
